name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MLFLOW_ARTIFACT_URI: file:./mlruns
  CSV_URL: "MLProject/seed_preprocessing.csv"
  TARGET_VAR: "TYPE"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: MLProject/conda.yaml
          activate-environment: ml-env
          python-version: "3.12.7"

      - name: Install extra pip packages
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          mlflow run ./MLProject -P dataset=seed_preprocessing.csv


      - name: Get latest MLflow run_id from model folder
        shell: bash -l {0}
        run: |
          RUN_ID=$(find mlruns/0 -type d -path "*/artifacts/model" | sort | tail -n1 | cut -d'/' -f3)
          if [ -z "$RUN_ID" ]; then
            echo "No MLflow model artifact found."
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id from model artifact: $RUN_ID"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        shell: bash -l {0}
        run: |
          echo "Checking model URI..."
          echo "Using run ID: $RUN_ID"
          ls -l "mlruns/0/$RUN_ID/artifacts/model"
          mlflow models build-docker --model-uri "mlruns/0/$RUN_ID/artifacts/model" --name weather-model

      - name: Tag Docker Image
        run: docker tag weather-model ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/weather-model:latest

      - name: Move MLflow artifacts to MLProject folder
        shell: bash -l {0}
        run: |
          mkdir -p MLProject/mlruns
          cp -r mlruns/0 "MLProject/mlruns/"

      - name: Push MLflow artifacts to GitHub
        shell: bash -l {0}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://github.com/${{ github.repository }}
          git add MLProject/mlruns/
          git commit -m "Add MLflow artifacts for run $RUN_ID" || echo "No changes to commit"
          git push origin main