name: CI Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlflow-train:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting MLflow training job..."

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.7

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0
        pip install cloudpickle==3.1.1
        pip install numpy==2.2.5 pandas==2.2.3 scikit-learn==1.6.1 scipy==1.15.3

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Get latest run ID
      id: get_run_id
      run: |
        RUN_ID=$(mlflow runs list -n 1 | awk 'NR==2 {print $1}')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest MLflow run ID: $RUN_ID"

    - name: Upload artifact to GitHub
      run: |
        mkdir -p artifact_upload
        MODEL_PATH=$(find mlruns -type d -name "model" | tail -1)
        cp -r "$MODEL_PATH" artifact_upload/
      continue-on-error: true

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: artifact_upload

    - name: Copy model to artifact_upload
      run: |
        MODEL_PATH=$(find mlruns -type d -name "model" | tail -1)
        mkdir -p artifact_upload
        cp -r "$MODEL_PATH" artifact_upload/

    - name: Build & Push Docker Image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        mlflow models build-docker -m artifact_upload/model -n mlflow-seed-model
        docker tag mlflow-seed-model ${{ secrets.DOCKER_USERNAME }}/mlflow-seed-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-seed-model:latest

